# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

# web icons
"messenger" = "ó°ˆ"
"facebook" = "ó°ˆŒ"
"youtube" = "ï…ª"
"stack overflow" = "ó°“Œ"
"medium" = "ïˆº"
"discord" = "ï‡¿"
"spotify" = "ï†¼"
"google" = "ï† "
"firefox" = "ï‰©"
"chrome" = "ï‰¨"

# file types
".rs" = "î¨"
".toml" = "îš²"
".conf" = "î˜•"
".ini" = "î˜•"
".pdf" = "ó°ˆ¦"
".cpp" = "î˜"
".hs" = "î·"
"makefile" = "î™³"
".cmake" = "î˜•"
"cmakelists" = "î˜•"
".css" = "î‰"
".md" = "ï’Š"
".cs" = "î™ˆ"
".html" = "îœ¶"
".exs" = "î˜­"
".erl" = "î±"
".sh" = "î¯Š"
".json" = "î˜‹"
".jsx" = "îº"
".js" = "î"
".xml" = "ó°—€"
".lua" = "î˜ "
".java" = "î¶¯"
# C is a very generic pattern so it sits at the bottom.
".f90" = "ó±ˆš"
".f" = "ó±ˆš"
".c" = "î˜"

# terminal icons
"nvim" = "îŸ…"
"vifm" = "ï¼"
"node" = "î´"
"ghci" = "î·"
"git" = "ó°Š¢"
"gh" = "îª„"
"python" = "îœ¼"
"tmux" = "î¯ˆ"
"bash" = "î¯Š"
"cava" = "ï€"
"alacritty" = "î•"
"kitty" = "î•"

"thunar" = "ï¼"
"dolphin" = "ï¼"
"discover" = "ïŠ"
"libreoffice calc" = "ó°±¾"
"libreoffice writer" = "ó°ˆ¬"
"okular" = "ó°ˆ¦"
"visual studio code" = "ó°¨"
"libreoffice" = "ó°ˆ”"
"gthumb" = "ï€¾"
"menu" = "ó°œ"
"game" = "ó°Š—"
"calculator" = "ï‡¬"
"kcalc" = "ï‡¬"
"transmission" = "ï€™"
"videostream" = "îšŸ"
"imv" = "ó°‹©"
"mpv" = "îšŸ"
"music" = "ï€"
"disk usage" = "ğŸ–¬"

[other]
fallback_icon = "î¬¯"
deduplicate_icons = false
