# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

# web icons
"messenger" = "ó°ˆ"
"facebook" = "ó°ˆŒ"
"stack overflow" = "ó°“Œ"
"medium" = "ïˆº"
"google" = "ï† "
"firefox" = "ï‰©"
"chrome" = "ï‰¨"

# file types
"rust" = "î¨"
".toml" = "îš²"
".conf" = "î˜•"
".ini" = "î˜•"
".pdf" = "ó°ˆ¦"
".cpp" = "î˜"
".hs" = "î·"
"makefile" = "î™³"
".cmake" = "î˜•"
"cmakelists" = "î˜•"
".cs" = "î™ˆ"
# C is a very generic pattern so it sits at the bottom.
".c" = "î˜"

# terminal icons
"nvim" = "îŸ…"
"vifm" = "ï¼"
"node" = "î´"
"ghci" = "î·"
"python" = "îœ¼"
"alacritty" = "ï„ "
"kitty" = "ï„ "

"thunar" = "ï¼"
"dolphin" = "ï¼"
"discover" = "ïŠ"
"libreoffice calc" = "ó°±¾"
"libreoffice writer" = "ó°ˆ¬"
"libreoffice" = "ó°ˆ”"
"gthumb" = "ï€¾"
"menu" = "ó°œ"
"calculator" = "ï‡¬"
"kcalc" = "ï‡¬"
"transmission" = "ï€™"
"videostream" = "îšŸ"
"imv" = "ó°‹©"
"mpv" = "îšŸ"
"music" = "ï€"
"disk usage" = "ğŸ–¬"

[other]
fallback_icon = "ğŸ¤¨"
deduplicate_icons = false
